repos:
    - repo: local
      hooks:
          - id: prettier
            name: run prettier
            entry: bash -c 'prettier -w .'
            language: system
            types: [bash]
            always_run: true
            verbose: true
